function GoogleRectangle() {
    return (
        <div>
            <div
          className="
            hidden
            lg:block
            overflow-hidden
            bg-google-red
            rounded-l-full
            absolute
            h-45
            w-2/4
            top-32
            right-0
            lg:
            -bottom-28
            lg:-right-36
            "
        ></div>
        <div
          className="
            hidden
            lg:block
            overflow-hidden
            bg-google-blue
            rounded-l-full
            absolute
            h-45
            w-2/4
            top-40
            right-0
            lg:
            -bottom-28
            lg:-right-36

            "
        ></div>
         <div
        className="
          hidden
          lg:block
          overflow-hidden
          bg-google-green
          rounded-l-full
          absolute
          h-45
          w-2/4
          top-48
          right-0
          lg:
          -bottom-28
          lg:-right-36
          "
      ></div>
        <div
        className="
          hidden
          lg:block
          overflow-hidden
          bg-google-yellow
          rounded-l-full
          absolute
          h-45
          w-2/4
          top-56
          right-0
          lg:
          -bottom-28
          lg:-right-36
          "
      ></div>
        </div>
    )
}

export default GoogleRectangle
